// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_cross_variance_cpp
double calc_cross_variance_cpp(NumericVector p1, NumericVector p2, NumericVector effects, NumericVector map, double max_dist);
RcppExport SEXP _UtilityFunctions_calc_cross_variance_cpp(SEXP p1SEXP, SEXP p2SEXP, SEXP effectsSEXP, SEXP mapSEXP, SEXP max_distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effects(effectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type map(mapSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist(max_distSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_cross_variance_cpp(p1, p2, effects, map, max_dist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_UtilityFunctions_calc_cross_variance_cpp", (DL_FUNC) &_UtilityFunctions_calc_cross_variance_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_UtilityFunctions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
