# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Gametic Variance for a Cross (Biparental)
#' 
#' Computes the expected genetic variance in the F2 population derived from crossing
#' two inbred parents, accounting for linkage disequilibrium.
#' 
#' @param p1 NumericVector. Genotype of Parent 1 (0 or 2).
#' @param p2 NumericVector. Genotype of Parent 2 (0 or 2).
#' @param effects NumericVector. Marker effects (a).
#' @param map NumericVector. Genetic map positions in Morgans.
#' 
#' @return double. The gametic variance.
#' 
#' @details 
#' Variance = Sum(Var_i) + 2 * Sum(Cov_ij)
#' Var_i = a_i^2 / 2  if segregating (P1 != P2)
#' Cov_ij = (1 - 2r_ij) * (a_i * a_j) / 2
#' where r_ij is recombination frequency calculated from Haldane map function:
#' r_ij = 0.5 * (1 - exp(-2 * |d_i - d_j|))
#' 
#' Assumes parents are fully homozygous inbred lines.
#' 
calc_cross_variance_cpp <- function(p1, p2, effects, map) {
    .Call(`_GenomicFlow_calc_cross_variance_cpp`, p1, p2, effects, map)
}

