# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Gametic Variance for a Cross (Biparental)
#'
#' Computes the expected genetic variance in the F2 population derived from
#' crossing two inbred parents, accounting for linkage disequilibrium.
#'
#' @param p1 NumericVector. Genotype of Parent 1 (0 or 2).
#' @param p2 NumericVector. Genotype of Parent 2 (0 or 2).
#' @param effects NumericVector. Marker effects (a).
#' @param map NumericVector. Genetic map positions in Morgans.
#' @param max_dist double. Maximum distance (in Morgans) to calculate
NULL

#'
#' @return double. The gametic variance.
#'
calc_cross_variance_cpp <- function(p1, p2, effects, map, max_dist = 3.0) {
    .Call(`_UtilityFunctions_calc_cross_variance_cpp`, p1, p2, effects, map, max_dist)
}

